stages:
  - publish-internal
  - publish-dockerhub

variables:
  INTERNAL_REGISTRY: nexus.pivlab.space:6001
  EXTERNAL_REGISTRY: pudge063
  BUILDER: custom_builder

.build:
  stage: publish-internal
  tags: [ immortal-dood ]
  before_script:
    - docker buildx use $BUILDER
  script:
    - export PUBLISH_TAG=${CI_COMMIT_TAG:-"$CI_COMMIT_SHA"}
    - |
      docker buildx b \
        --provenance=false \
        --platform linux/amd64 \
        -f ${COMPONENT}/Dockerfile \
        -t ${PUBLISH_PATH}:${PUBLISH_TAG} \
        --push ${COMPONENT}/
  rules:
    - changes:
        - $COMPONENT/*

build:fm-client:
  variables:
    COMPONENT: fm_client
    PUBLISH_PATH: ${INTERNAL_REGISTRY}/${COMPONENT}
  extends: [ .build ]

build:fm-server:
  variables:
    COMPONENT: fm_server
    PUBLISH_PATH: ${INTERNAL_REGISTRY}/${COMPONENT}
  extends: [ .build ]

build:fm-client-dockerhub:
  stage: publish-dockerhub
  variables:
    COMPONENT: fm_client
    PUBLISH_PATH: ${EXTERNAL_REGISTRY}/fm-client
  extends: [ .build ]
  when: manual
  needs: [ build:fm-client ]
  rules:
    - if: "$CI_COMMIT_TAG"
    - changes:
        - $COMPONENT/*

build:fm-server-dockerhub:
  stage: publish-dockerhub
  variables:
    COMPONENT: fm_server
    PUBLISH_PATH: ${EXTERNAL_REGISTRY}/fm-server
  extends: [ .build ]
  when: manual
  needs: [ build:fm-server ]
  rules:
    - if: "$CI_COMMIT_TAG"
    - changes:
        - $COMPONENT/*
