stages:
  - jobs

variables:
  NEXUS_URL: nexus.pivlab.space
  NEXUS_PORT: 6001
  BUILDER: custom_builder
  CI_COMMIT_TAG: 1.0.1

.build:
  stage: jobs
  tags: [ immortal-dood ]
  before_script:
    - docker buildx use $BUILDER
  script:
    - |
      docker buildx b \
        --provenance=false \
        --platform linux/amd64 \
        -f ${COMPONENT}/Dockerfile \
        -t $NEXUS_URL:$NEXUS_PORT/${COMPONENT}:${CI_COMMIT_TAG:-"$CI_COMMIT_SHA"} \
        --push ${COMPONENT}/
  rules:
    - if: "$CI_COMMIT_TAG"
    - changes:
        - $COMPONENT/*

build:fm-client:
  variables:
    COMPONENT: fm_client
  extends: [ .build ]

build:fm-server:
  variables:
    COMPONENT: fm_server
  extends: [ .build ]
